---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx service
      command: service nginx status

    - name: verify nginx is listening on 80
      wait_for: port=80 timeout=10


- hosts: ap01
  become: true
  tasks:
    - name: verify apach2 service
      command: service apache2 status

    - name: verify apache is listening on 80
      wait_for: port=80 timeout=10

- hosts: ap02
  become: true
  tasks:
    - name: verify apach2 service
      command: service apache2 status

    - name: verify apache is listening on 80
      wait_for: port=8081 timeout=10